import type { IconBaseProps } from "react-icons";
import {
  FaArrowLeft,
  FaArrowRight,
  FaArrowTrendDown,
  FaArrowTrendUp,
  FaBagShopping,
  FaBell,
  FaBox,
  FaBoxOpen,
  FaCamera,
  FaCheck,
  FaCircleCheck,
  FaClockRotateLeft,
  FaHouse,
  FaMagnifyingGlass,
  FaMinus,
  FaMoon,
  FaPhone,
  FaPlus,
  FaReceipt,
  FaSun,
  FaTrash,
  FaTriangleExclamation,
  FaTruckRampBox,
  FaUserPlus,
  FaUsers,
  FaWallet,
} from "react-icons/fa6";

export type IconProps = IconBaseProps;

export {
  FaHouse as HomeIcon,
  FaReceipt as ReceiptIcon,
  FaWallet as WalletIcon,
  FaBox as BoxIcon,
  FaUsers as UsersIcon,
  FaPlus as PlusIcon,
  FaMinus as MinusIcon,
  FaTrash as TrashIcon,
  FaCheck as CheckIcon,
  FaCircleCheck as CheckCircleIcon,
  FaUserPlus as UserPlusIcon,
  FaBagShopping as BagIcon,
  FaPhone as PhoneIcon,
  FaArrowTrendUp as TrendUpIcon,
  FaArrowTrendDown as TrendDownIcon,
  FaBell as BellIcon,
  FaArrowRight as ArrowRightIcon,
  FaArrowLeft as ArrowLeftIcon,
  FaTriangleExclamation as AlertIcon,
  FaSun as SunIcon,
  FaMoon as MoonIcon,
  FaMagnifyingGlass as SearchIcon,
  FaCamera as CameraIcon,
  FaTruckRampBox as InboxInIcon,
  FaBoxOpen as PackageIcon,
  FaClockRotateLeft as HistoryIcon,
};
